//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CozmoDemo
{
    [Serializable]
    public class DrivePathMsg : Message
    {
        public const string k_RosMessageName = "cozmo_demo_msgs/DrivePath";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg[] points;
        public int arrLength;

        public DrivePathMsg()
        {
            this.points = new Geometry.PointMsg[0];
            this.arrLength = 0;
        }

        public DrivePathMsg(Geometry.PointMsg[] points, int arrLength)
        {
            this.points = points;
            this.arrLength = arrLength;
        }

        public static DrivePathMsg Deserialize(MessageDeserializer deserializer) => new DrivePathMsg(deserializer);

        private DrivePathMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.points, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.arrLength);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.points);
            serializer.Write(this.points);
            serializer.Write(this.arrLength);
        }

        public override string ToString()
        {
            return "DrivePathMsg: " +
            "\npoints: " + System.String.Join(", ", points.ToList()) +
            "\narrLength: " + arrLength.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
