//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CozmoDemo
{
    [Serializable]
    public class HeadRotMsg : Message
    {
        public const string k_RosMessageName = "cozmo_demo_msgs/HeadRot";
        public override string RosMessageName => k_RosMessageName;

        public float x;

        public HeadRotMsg()
        {
            this.x = 0.0f;
        }

        public HeadRotMsg(float x)
        {
            this.x = x;
        }

        public static HeadRotMsg Deserialize(MessageDeserializer deserializer) => new HeadRotMsg(deserializer);

        private HeadRotMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
        }

        public override string ToString()
        {
            return "HeadRotMsg: " +
            "\nx: " + x.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
