//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CozmoDemo
{
    [Serializable]
    public class TurnInPlaceMsg : Message
    {
        public const string k_RosMessageName = "cozmo_demo_msgs/TurnInPlace";
        public override string RosMessageName => k_RosMessageName;

        public float angle;
        public float speed;

        public TurnInPlaceMsg()
        {
            this.angle = 0.0f;
            this.speed = 0.0f;
        }

        public TurnInPlaceMsg(float angle, float speed)
        {
            this.angle = angle;
            this.speed = speed;
        }

        public static TurnInPlaceMsg Deserialize(MessageDeserializer deserializer) => new TurnInPlaceMsg(deserializer);

        private TurnInPlaceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.angle);
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.angle);
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "TurnInPlaceMsg: " +
            "\nangle: " + angle.ToString() +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
