//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CozmoDemo
{
    [Serializable]
    public class DriveStraightMsg : Message
    {
        public const string k_RosMessageName = "cozmo_demo_msgs/DriveStraight";
        public override string RosMessageName => k_RosMessageName;

        public float distance_mm;
        public float speed_mmps;

        public DriveStraightMsg()
        {
            this.distance_mm = 0.0f;
            this.speed_mmps = 0.0f;
        }

        public DriveStraightMsg(float distance_mm, float speed_mmps)
        {
            this.distance_mm = distance_mm;
            this.speed_mmps = speed_mmps;
        }

        public static DriveStraightMsg Deserialize(MessageDeserializer deserializer) => new DriveStraightMsg(deserializer);

        private DriveStraightMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.distance_mm);
            deserializer.Read(out this.speed_mmps);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.distance_mm);
            serializer.Write(this.speed_mmps);
        }

        public override string ToString()
        {
            return "DriveStraightMsg: " +
            "\ndistance_mm: " + distance_mm.ToString() +
            "\nspeed_mmps: " + speed_mmps.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
