teleop_node:
  axis_linear: 1
  scale_linear: 0.1
  scale_linear_turbo: 0.2
  axis_angular: 0
  scale_angular: 1.2
  scale_angular_turbo: 2.4
  enable_button: 6
  enable_turbo_button: 7
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
